### ISSUE TITLE
The argument 'nameOrConnectionString' cannot be null, empty or contain only white space.

### ISSUE THREAD

**Issue by jimbo74** [mrahhal/Migrator.EF6#33] opened 2017-01-17 10:23 UTC
When trying to add a new migration passing in a connection string I get the above error.

My command is similar to:
dotnet ef migrations add TestClassAdded --connection-string "Server=xxx;Database=yyy;etc.."

The tool compiles my project and then states:

Using provided connection string as an override.
The argument 'nameOrConnectionString' cannot be null, empty or contain only white space.

I have successfully done the initial create (with connection string hard coded) and the update database following this (passing in the connection string) but now I get this strange result when trying to add another migration where it tells me it's using the connectionstring but then doesn't

**Comment by mrahhal** [comment] 2017-01-17 11:33
Is there a stacktrace with the error?

**Comment by mrahhal** [comment] 2017-01-17 11:40
Ok so, we're looking at [this](https://github.com/mrahhal/Migrator.EF6/blob/e8d8f6c64532746aeda93a96155a2350e50e0722/src/Migrator.EF6.Tools/Executor.cs#L223-L224) piece of code:
```cs
if (_connectionString != null)
{
    Console.WriteLine("Using provided connection string as an override.");
    dbMigrationsConfiguration.TargetDatabase = new DbConnectionInfo(_connectionString, _providerName);
}
```

The only reason that error would happen is if the connection string is all whitespace. That's weird.

**Comment by jimbo74** [comment] 2017-01-17 11:41
This is a print of the command and error:

![migrations error](https://cloud.githubusercontent.com/assets/3542236/22019093/e5095778-dca9-11e6-9cae-d3c3ecffcd81.jpg)

**Comment by mrahhal** [comment] 2017-01-17 11:47
- What version are you on?
- Can you run the other commands or does the same error occur? (`migrations list` for example)

**Comment by jimbo74** [comment] 2017-01-17 11:55
version 1.0.8

I get the same error with the other commands

**Comment by mrahhal** [comment] 2017-01-17 12:14
Are you by any chance using localdb? Doesn't look like it, but now I remembered that in my tests localdb didn't work when you specify the connection string from the command line (so I used sqlexpress). Now, the error here is completely different anyway, it doesn't make much sense. The "_connectionString" variable is only every written to by the command line parser ("Microsoft.DotNet.Cli.Utils"). 

Would the same issue occur if you try with a fresh project (+ sqlexpress)? Because it's working fine on my machine (yeah I know).

**Comment by jimbo74** [comment] 2017-01-17 12:17
I'm using a database on azure, I can try a new project with sqlexpress but that isn't my end goal so I don't see what I'll get from that.

Thanks for your help with this though

**Comment by mrahhal** [comment] 2017-01-17 12:19
Problem is I can't think of something that might lead to this error.
If @DOTang would be so kind to give his input. Are you still using this option (specifying the connection string in the command line)? If so is it working okay for you?

**Comment by jimbo74** [comment] 2017-01-17 12:22
Yes I saw @DOTang was trying to do something similar which is what led me to this.
Lets see what he says

**Comment by DOTang** [comment] 2017-01-17 18:45
I use the connection string in the command, I use a normal SQL DB, not express or azure though.

**Comment by mrahhal** [comment] 2017-01-17 23:04
Hmm maybe the problem is related to Azure? I'm seeing the same expected behavior on my end.

**Comment by mrahhal** [comment] 2017-02-03 16:29
I'm closing this, please reopen if you still have issues.

**Closed as completed by mrahhal** 2017-02-03 16:29 UTC
