### ISSUE TITLE
VS 2017 format

### ISSUE THREAD

**Issue by hikalkan** [mrahhal/Migrator.EF6#36] opened 2017-03-09 12:28 UTC
Hi,

I have just migrate my solution to VS 2017. Everything works except EF migration command line. I was using Migrator.EF6 for project.json format, but now there is no project.json and it throws given error when I use update-database command:

````
Unhandled Exception: System.IO.FileNotFoundException: Could not find file '...\project.json'.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectPath, ProjectReaderSettings settings)
   at Migrator.EF6.Tools.Program.Dispatch(String[] args)
   at Migrator.EF6.Tools.Program.Main(String[] args)
````

Do you know any way of using EF6 with VS 2017 format?

Thanks.

**Comment by mrahhal** [comment] 2017-03-09 12:30
You can follow along in #35 which works right now, but I still have a couple of things to improve.

**Comment by hikalkan** [comment] 2017-03-09 12:37
Thanks a lot for the information. When it's being released :)

**Comment by mrahhal** [comment] 2017-03-09 12:39
Probably today if all goes well. I want to get this out ASAP. I'll close this issue when I release so you'll be notified.

**Comment by hikalkan** [comment] 2017-03-09 12:40
Thank you very much. This is the only blocker for us now. Thank you for your valuable work to make EF6 working with AspNet Core since as I see there is no other way of it.

**Comment by mrahhal** [comment] 2017-03-09 14:21
`1.1.0` is released. Please report issues if you find any unexpected behaviors. Note that `net46` is required now because the cli package requires it.

**Closed as completed by mrahhal** 2017-03-09 14:21 UTC

**Comment by hikalkan** [comment] 2017-03-09 14:48
It seems working in my first tests. I will inform you if have any problem.
Thanks a lot such a fast return to this issue.
